### ISSUE TITLE
AddASPathSegment(asSeg...) is appending only first AS number

### ISSUE THREAD

**Issue by cprabha** [openconfig/featureprofiles#1659]
Hi,

With current code AddASPathSegment(asSeg...) option in ATE is appending only the first AS number.

For eg., with below code , only first AS in list 65505 is seen in the routes received in the DUT from ATE.
asSeg := []uint32{65505, 65501, 65503}
bgpNeti1.BGP().WithNextHopAddress(ateSrc.IPv4).AddASPathSegment(asSeg...).WithTypeSEQ()

Also gnmi get on ATE fails if "WithTypeSet" is used .

script code:    ASseg := []uint32{65501, 600}, WithTypeSet option

Error:
    bgp_remove_private_as_test.go:263: Await(t) on ate(10.92.196.126) at /network-instances/network-instance[name=atedst]/protocols/protocol[identifier=BGP][name=0]/bgp/rib/afi-safis/afi-safi[afi-safi-name=IPV4_UNICAST]/ipv4-unicast/neighbors/neighbor[neighbor-address=*]/adj-rib-in-pre/routes/route[path-id=0][prefix=*]/state/prefix: error receiving gNMI response: failed to append details for elem 0: invalid AS path string: "<500 100> {65501}"

Can you please help fix this issue?

Thanks,
Prabha

**Comment by greg-dennis** [comment]
@cprabha the error in the gnmi response when using WithTypeSet is a bug that I will fix.

The issue of "only first AS in list 65505 is seen in the routes received in the DUT from ATE" is not necessarily a bug in Ondatra. The question there is whether IxNetwork is configured correctly. Can you check whether IxNetwork is configured to have all three "65505, 65501, 65503" in the AS path segment? If it is, then the Ondatra contract (to configure IxNetwork correctly) has been met.

**Comment by cprabha** [comment]
Hi Greg,

I did check routes on ATE , it shows first AS number even though three as segments are set in API.

***@***.***

Thanks,
Prabha

**Comment by cprabha** [comment]
<img width="498" alt="asseg" src="https://github.com/openconfig/featureprofiles/assets/29638902/f67d300c-4e4f-4cd4-b252-2b901bac5248">

**Comment by ANISH-GOTTAPU** [comment]
![image](https://github.com/openconfig/featureprofiles/assets/48308607/724bbc38-6c43-4b5c-9b33-c228cc969f69)

Based on Number of As Segments the `Number of AS# In Segment` needs to be updated.
Raised PR https://github.com/openconfig/ondatra/pull/76 to fix the issue

**Comment by greg-dennis** [comment]
The PR from @ANISH-GOTTAPU fixes the first issue.
I am working on the gnmi issue right now.
I'll comment back when both fixed are merged into Ondatra.

**Comment by greg-dennis** [comment]
This is fixed in the latest Ondatra release https://github.com/openconfig/ondatra/releases/tag/v0.1.16
I'll update featureprofiles to require this release

**Comment by cprabha** [comment]
Thanks Greg.

-Prabha.

**Comment by cprabha** [comment]
Hi Greg,

I am still seeing issue with as path on ATE. It shows different AS number then which is configured one on sent routes.

Routes sent to ATE have as paths : 500 100 65501 65507 65554 

on ATE it shows : 500 100 65501 65507 23456

I have attached screen shot from ixia . please check.

Thanks,
Prabha

**Comment by cprabha** [comment]
<img width="947" alt="asSeg1" src="https://github.com/openconfig/featureprofiles/assets/29638902/069a23f3-9543-45ab-a510-ee7754ab2b34">

**Comment by cprabha** [comment]
Also this path can contain as path as {65501} when SET mode is used. 
so return value need to be changed from uint32 to different value ?

**Comment by greg-dennis** [comment]
@cprabha, I'm not clear on why uint is a problem here? 65501 is a valid uint. It seems the problem is that Ixia is now comma-separating the segment members as opposed to separating them with whitespace? I have only seen it whitespace separated in IxNetwork -- maybe it's version dependent? @ANISH-GOTTAPU, the segment members can be either space-separated or comma-separated in the learned info?

**Comment by greg-dennis** [comment]
@cprabha, could you link me to a draft PR that repro's the issue, too?

**Comment by greg-dennis** [comment]
@ANISH-GOTTAPU, in @cprabha's first comment above the error shows as `invalid AS path string: "<500 100> {65501}"`. That's a space between 500 and 100, and that's what I've see in IxNetwork. Is it sometimes spaces and sometimes commas?

**Comment by cprabha** [comment]
@greg-dennis I have added script for both "SET"  and "SEQ" (currently working fine) . please check.

https://github.com/cprabha/featureprofiles/blob/AsPathSet/feature/bgp/aspath/ate_tests/bgp_remove_private_as_new_test.go

In both Seq and Set mode it is space separated, in Set mode it adds {} to those AS numbers which are added using Set mode.

**Comment by greg-dennis** [comment]
@cprabha, sorry what's the status of this? Do you still have an issue here? Any knowledge of the what the brackets mean in "[800 65501 600]"?

**Comment by cprabha** [comment]
@greg-dennis ,  There are multiple modes in AS PATH . SET , SEQ  , SET confed, SEQ confed. 
We might see different pattern in each of these modes. 
I have tested SET and SEQ , SEQ is space separated and SET has pair of {}.

**Comment by cprabha** [comment]
I could not find any document around this pattern  to share.

**Comment by greg-dennis** [comment]
I found it is comma-separated in SETs and space-separated in SEQs. Example:

`<500 100> {65501,65507,65534}`

Weird. I'll try to make the parsing logic robust to both.

**Comment by greg-dennis** [comment]
This is fixed in the latest Ondatra release https://github.com/openconfig/ondatra/releases/tag/v0.1.23

**Comment by cprabha** [comment]
Thanks @greg-dennis .

**Comment by cprabha** [comment]
@greg-dennis , looks like these changes are not merged in otg. I am not getting AS numbers appended at OTG. 
Please could you check.

**Comment by greg-dennis** [comment]
@cprabha, IxNetwork and OTG gnmi are entirely separate. IxNetwork gNMI is provided by a server that Google wrote and is embedded in Ondatra. OTG provides an entirely different yang model. I don't know whether they model the as path segments, but you'd have to take a look at the OTG yang models or ask Keysight.

**Comment by cprabha** [comment]
> @cprabha, IxNetwork and OTG gnmi are entirely separate. IxNetwork gNMI is provided by a server that Google wrote and is embedded in Ondatra. I take responsibility for fixing issues there. OTG provides an entirely different yang model. I don't know whether they model the as path segments, but you'd have to take a look at the OTG yang models or ask Keysight. As you may be aware, it's our goal to move entirely to OTG and deprecate IxNetwork.

Thanks @greg-dennis . I have opened issue under otg for ixia to help on this issue in otg.
